### ISSUE TITLE
collaction.org server down 

### ISSUE THREAD

**Issue by brinerustle** [CollActionteam/CollAction#294]
neither IP seems to respond to ping:

$ ping -c 4 collaction.org
PING collaction.org (**54.93.225.61**) 56(84) bytes of data.

--- collaction.org ping statistics ---
4 packets transmitted, 0 received, 100% packet loss, time 3063ms

$ ping -c 4 collaction.org
PING collaction.org (**52.57.99.221**) 56(84) bytes of data.

--- collaction.org ping statistics ---
4 packets transmitted, 0 received, 100% packet loss, time 3066ms

**Comment by ronvdakker** [comment]
Thanks @brinerustle ! We had some heavy traffic at the time and couldnt handle it. We are currently working on improving the scalability of the platform. Thanks again for sharing - very helpful!
