### ISSUE TITLE
Create a user "profile" page 

### ISSUE THREAD

**Issue by ronvdakker** [CollActionteam/CollAction#33]
Requirements:
-A user should be able to import basic detail from Facebook or Linkedin
-A user should be able to add and change profile detail manually (photo, username, email, country)
-A user should be able to express his/her interests in certain topics (Should correspond to labels - e.g. environment, community, etc.)
-A user should be able to view his current and past supported project in his/her profile
-In the long term, user should be able to  collect points for joining and participating projects
-User should be able to share profile on social media

**Comment by efel85** [comment]
History of current and past supported projects could be something in the style of a facebook timeline.
